### PR TITLE
Unicode for nwggrid, a bit of refactoring

### PR DESCRIPTION
**Pull request by Siborgium**

### CODE REVIEW

**Comment by nwg-piotr** [comment]
I was working on the grid search box last night on another branch, but probably your solution is better. Will take a closer look at home.

**Comment by Siborgium** [comment]
Oh, sorry about that. Feel free to ask questions, I'd be glad to have my code reviewed. Don't merge yet, I've noticed that the SearchEntry omits space for some reason.
Also, I would like to dig into icons loading in the next few days, is it ok?

**Comment by nwg-piotr** [comment]
Whatever is going to be done soon, should be finished till this weekend. Later I'm off for lakes (11 days).

**Comment by nwg-piotr** [comment]
> SearchEntry omits space for some reason

Looks as if `Gtk::SearchEntry::handle_event` didn't handle `GDK_KEY_space`.

**Comment by Siborgium** [comment]
Well, since it seems to work, I'd believe it's finished.
I was unable to speed up icon loading, the only open possibility is to use asynchronous loading which is hard to incorporate. I see no reason to rewrite already working functionality either. As such, I won't be pushing commits anytime soon.
Thank you for your work, these applications are really nice to use. I am glad I was able to improve them.

**Comment by nwg-piotr** [comment]
As I see, it was quite tricky to make the space key work. :)

What seems to speed up icons loading most is the icon theme. Replacing Adwaita with Papirus speed it up in the way visible to naked eye.

After merging your PR, I'll publish a release on Saturday or Sunday, if testing goes well. Then I'm having a brake, as mentioned above. Thank you very much for your contribution.

**Pull request merged**
