### PR TITLE
github actions: fix build status badge in readme

### PR DESCRIPTION
**Pull request by Siborgium**

### CODE REVIEW

**Comment by Siborgium** [comment]
I'll set up more jobs before merging.

**Comment by nwg-piotr** [comment]
Whatever you want. I'll be AFK till late night.

**Comment by Siborgium** [comment]
Builds work fine, but it fails to find gtk-layer-shell because ubuntu 20.04 [only has version 0.1.0](https://repology.org/project/gtk-layer-shell/versions).

**Review by nwg-piotr — APPROVED** [review]
I don't care much about Ubuntu.

**Comment by Siborgium** [comment]
Fair enough, but this is default linux image on Github Actions. We could setup a vm just like we did for FreeBSD though.

**Comment by nwg-piotr** [comment]
It's up to you. As a hobbyist, I'm not not yet self-developed enough to appreciate CI. ;)

**Pull request merged**
