### PR TITLE
Alternative pin/unpin implementation, faster parsing

### PR DESCRIPTION
**Pull request by Siborgium**
While you were supposedly taking a break, I wanted to implement pin/unpin not closing the application. But you've done the same, so I think it would be wise to provide my implementation.

I've reworked internal structure of grid's MainWindow object. All boxes are stored in one place now, they were given a tags according to which pointers to them are arranged. Working with pointers instead of actual objects allows for simpler and faster manipulations.

Also, I've took my time and rewrote DesktopEntry parser. While not so straightforward, it gives me avg boost of 10-15ms.

This is a draft for there is a number of issues I'd like to address before merging.

- [x] When pinning/unpinning, the grid should remain sorted;
- [x] Number of desktop entries is not shown on startup (the first box receives focus somehow);
- [x] Sometimes, if pinning/unpinning too many items (for me it usually takes pinning all the apps and then unpinning them all back), the logic breaks;
- [x] Double-check if boxes are loading correctly (favourites bug);
- [ ] Provide explanatory comments where needed.

As far as I could test, what I've done fixes favourites. I've reordered the way we load the boxes (pins first, then favourites, then the rest). Because string::empty should return true on moved-from strings, it should be sufficient to avoid this issue. Yet, I'd like to be double-sure.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
> Working with pointers instead of actual objects

LOL, pointers are still giving me headache 👍 

As you know, you're on you own until I'm back home (21 August). Purposely I don't take any Linux machine along with me, while going on vacation. 

We both need to pay more attention to testing. Better to release later, than to seek bugs in hurry.

**Comment by nwg-piotr** [comment]
Are you aware that I'm still having conflicting files?

image

**Comment by Siborgium** [comment]
I've encountered the problem that is not easily avoided: each grid/vector (pins, favs, the rest) require their own sorting. I've tried several ways of solving this problem, and none of them are neither nice nor decently working. The hardest issue I try to work around is that when Gtk widget gets removed from its container, it leaves empty space. Container works as if that empty space contains actual widget. Inserting a widget is also hard, as it requires all other widgets to be shifted by one. Filtering further complicates it.

Another option I've come up with is to replace Gtk Grid with Gtk FlowBox. It is available since Gtk 3.12 which came out in 2014. Quick test works fine, and our code can be simplified by a large degree, but we'll face new issues in this case. Because you're the author, I'd like to hear your opinion before making any actual changes.

**Comment by nwg-piotr** [comment]
I have never used GtkFlowBox, so have no opinion. I have read the class description, and found this excerpt worrisome:

> The size request of a GtkFlowBox alone may not be what you expect; if you need to be able to shrink it along both axes and dynamically reflow its children, you may have to wrap it in a GtkScrolledWindow to enable that.

One way or another, I think that having 2 separate grids (/FlowBoxes) at a time (I don't expect users to use -f and -p together) simplifies the code. I didn't really plan on many improvements  to this project, as my C++ is still less than basic. However, the thing which I would like to implement - if any at all! - is pinning/unpinning icons without closing the window. This would require resorting and rebuilding both grids, since - as you noticed - removing a widget leaves the empty place.

Shortly: I don't think we should complicate the code significantly just in order to speed up launching of 15 ms. It's unnoticeable.

**Comment by Siborgium** [comment]
First of all, I'd like to apologize for a long delay, I've been a bit busy. 

After few experiments I've come to the following conclusion: flowbox is not an option. The code is much simpler, yet I couldn't manage to properly align favs and pins. You can take a look at the code [here](https://github.com/Siborgium/nwg-launchers/tree/flowbox).

>I think that having 2 separate grids (/FlowBoxes) at a time (I don't expect users to use -f and -p together) simplifies the code

Sure! I had no intentions to change the way it is designed.

>This would require resorting and rebuilding both grids

And that's the hard part. The algorithm itself is simple, but GTK gets in the way.

> I would like to implement - if any at all! - is pinning/unpinning icons without closing the window

It has been done already.

>I don't think we should complicate the code significantly just in order to speed up launching of 15 ms. It's unnoticeable.

While I do agree with the statement overall, I don't consider my changes more complicated compared to the original, especially those I did to parser part. 15ms is unnoticeable for sure, yet if this speedup could be achieved with little to no cost, then why not?

**Comment by nwg-piotr** [comment]
Welcome back, Sergey :)

Let me apologize as well: I'm very happy to have couple of well skilled C/C++ programmers on board, but please keep in mind that I'm just an after hours coder, with some experience in python and Java, and hardly any in C++. As you might have noticed, in the meantime several PRs have been merged - to allow custom background colours (by me), to list flatpak .desktop files (me and @GabMus), and to better handle PID files and tidy up nwg_tools.h (by @ericonr). For now I'm wasting my life at the office, with no Linux machine in range, but I'm seeing conflicting `grid/grid.cc` and `grid/grid_tools.cc` files. If it's not a problem, it would be not bad to apply your changes to the current master branch.

For further development, as stated in [CONTRIBUTING.md](https://github.com/nwg-piotr/nwg-launchers/blob/master/CONTRIBUTING.md), I'd be grateful for following the rule **bug fixes first**, including not only sway, but also i3 and Openbox. It seems that at some point the X windows compatibility has been broken. I'm not yet quite sure if it's my machine only, but at the moment the main window is 100% opaque, and also the dmenu positioning does not work. When possible, I'll check it once again and submit issues if necessary.

**Comment by Siborgium** [comment]
>with some experience in python and Java, and hardly any in C++

And I am happy to help.

>If it's not a problem, it would be not bad to apply your changes to the current master branch.

Good! I am going to make my fork ready to merge before tomorrow. I've synced local copy already, now I just need to check if everything is alright and make some minor tweaks.

**Comment by Siborgium** [comment]
Just noticed that the key navigation doesn't work properly.

**Comment by Siborgium** [comment]
Should work fine now.

**Comment by nwg-piotr** [comment]
> I've synced local copy already

Alright then. I'm in the process of fixing #99 , but I'll hold pushing changes until your new code is merged. Make sure if your fork is really up to date at  the moment:

image

**Comment by Siborgium** [comment]
For now, the only problem I encounter is ugly filtered view. This is, again, has to be fixed with `max_children_per_line`, but I have no idea for now. I hope I'll manage to fix it soon.

**Comment by nwg-piotr** [comment]
OK, I'm still stuck at the office, no hurry. :) Won't turn on my own machine earlier than in 10 hours.

BTW: I still see conflicts in `grid/grid.cc` and `grid/grid_tools.cc`.

**Comment by Siborgium** [comment]
Speaking of merge conflicts, I am aware of them. I've synced with master twice (back then and today), and I couldn't find any missed parts yet, so it should be ok.

**Comment by nwg-piotr** [comment]
Could you check if your branch includes commits from #100  ?

**Comment by Siborgium** [comment]
Sure! They are included in the latest merge commit.

**Comment by nwg-piotr** [comment]
I'll be unable to resolve the conflicts in the web interface:

image

**Comment by Siborgium** [comment]
Don't worry, I'm still fixing minor issues.

**Comment by nwg-piotr** [comment]
This will need to merged, sooner or later. :)

**Comment by Siborgium** [comment]
For now, let's consider it done. Please, take your time and test it to ensure there is no obvious bugs/things you'd like to fix before it is merged.

**Comment by nwg-piotr** [comment]
Also I see no conflicts now. OK, I'll be testing tonight.

**Comment by nwg-piotr** [comment]
Looks very well, but seems to need some more work.

## Serious issues

- If search results don't fill the screen vertically, they become badly formatted.

2020-09-03-003525_screenshot

- Up to 8 icon columns available. If (num_col > 8) (e.g. `nwggrid -f -n 10`), actual number of columns on the screen remains 8. Number of favourites icons is 10, but formatted in 2 rows (8 + 2).

2020-09-03-004351_screenshot


## Minor issues

- After installing the new version, 1 of 6 old pinned icons left for some reason. Not really an issue.

- No gain on speed. Actually `nwggrid -p` used to display "Time: 190" (up to 200) on my machine, now it's 220 on average. Not an issue to me.

- After installing the new version, I had the number of favourites limited to 5, regardless of the number of grid columns.  Deleting the cache file seems to have helped. Not an issue, if mentioned somewhere in README. Or we could just use another cache filename (the old one should be removed if found).

**Comment by Siborgium** [comment]
>If I right-click an icon to pin it (the window remains open), and then left-click whichever pinned icon to launch a program, the left-clicked icon gets unpinned.

Weird. On my machine it works as expected.

>Up to 8 icon columns available. If (num_col > 8) (e.g. nwggrid -f -n 10), actual number of columns on the screen remains 8. Number of favourites icons is 10, but formatted in 2 rows (8 + 2).

Changing `min_children_per_line` accordingly seems to work.

>If search results don't fill the screen vertically, they become badly formatted.

Thanks,  the code you suggested seems to fix it.

>nwggrid -f: while searching, the favourites line stops being displayed (in contrary to the -p mode). In result searching the app, which is a favourite gives no result. Maybe it should behave like nwggrid -p does: don't hide the favourites line?

This is how it works in `master`. Changing it would make code a lot simpler, though.

**Comment by Siborgium** [comment]
Interestingly, I too can observe different pins/favs before and now. I guess it is because the loading order has been changed.

>no gain on speed

Well, on my machine there is a certain gain (30-40ms avg). I guess it is because of my old HDD.

**Comment by nwg-piotr** [comment]
> This is how it works in master.

Sure. Just thought it's time to give both `-p` and `-f` the same behaviour.

**Comment by nwg-piotr** [comment]
I've just noticed: in `grid_classes.cc` line 32

```
searchbox.set_placeholder_text("Type to search");
```

seems not to work. The search box appears initially empty. If I hit Delete while searching, it sets the placeholder to "Type to search". Can't take a closer look, as it's 3:20 am, and I'll have to wake up in 3,5 h. :)

**Comment by Siborgium** [comment]
Good night :)

**Comment by Siborgium** [comment]
Speaking of searchbox:

There is no placeholder text initially because it is focused at startup. If it loses focus somehow, placeholder appears again.

The problem is, we can't just remove focus, it needs to be moved somewhere. Besides searchbox, only boxes can be focused. Once we move focus to the box, it overwrites description text (total count of boxes initially). Possible solutions are:

 - Just remove the initial number of boxes. The simplest solution.
 - Once box loses focus, restore the initial text. It'd take some additional code: add `on_focus_out_event` override, keep track of the actual number of boxes in `MainWindow`. Nothing special.
 - ???

**Comment by nwg-piotr** [comment]
> Besides searchbox, only boxes can be focused. Once we move focus to the box, it overwrites description text (total count of boxes initially)

The number of boxes is just a meaningless placeholder to me. What should be focused first IMO is the first box in either favourites or pinned icons.

**Comment by Siborgium** [comment]
They were sorted by clicks, that's right. I've set sort func unintentinally.

**Comment by nwg-piotr** [comment]
What still bothers me is what I described as **issue 3** above, especially if you can not reproduce it on your side. I'll try to take closer look at it tonight.

**Comment by Siborgium** [comment]
It may happen because the loading order has been changed.
Try clearing your pins cache (rename it, or just delete), I hope it'll help.

**Comment by nwg-piotr** [comment]
OK, I'll try. I'll be working as usually since 11 pm CET.

**Comment by nwg-piotr** [comment]
> Try clearing your pins cache (rename it, or just delete), I hope it'll help.

It doesn't help.

Steps to reproduce:

1. run `nwggrid -p`;
2. right-click one or more icon to pin it/them up;
3. left-click one of pinned icons to run the program;
4. run `nwggrid -p` again;

Expected behaviour: all the previously pinned icons still visible;

Actual behaviour: left-clicked icon disappeared.

There must be a bug in the code.

**Comment by Siborgium** [comment]
I understand, but I fail to reproduce this issue. I'll dig into it.

**Comment by nwg-piotr** [comment]
> I fail to reproduce this issue

Just in case the environment made the difference: sway on Arch Linux here. Haven't yet tested this certain issue on other WMs.

**Comment by Siborgium** [comment]
Try the latest commit, does it help?

**Comment by nwg-piotr** [comment]
Sorry, AFK till the late evening. I only have my Chromebook here.

**Comment by nwg-piotr** [comment]
> Try the latest commit, does it help?

It's all right. Well done.

**Comment by nwg-piotr** [comment]
The change in parsing seems to have resulted in a different attitude to trailing spaces in the `exec` field, which results in doubled entries for the same application, if the old `nwg-fav-cache` remains in use. Old lines should be irrelevant from now on, but - for some reason - favourites behave oddly, as I mentioned in **Minor issues** above. I'm afraid the same issue may apply to `nwg-pin-cache`. We should create the cache files from scratch.  

I think we should use another filenames, but this will leave old, useless files in the cache folder. We could delete them programmatically if found, or just ask users to delete them manually (in release notes / README). Tell me what you think. 

```json
{
  "/usr/bin/chromium": 2,
  "/usr/bin/chromium ": 3,
  "MOZ_ENABLE_WAYLAND=1 /usr/lib/firefox/firefox ": 2,
  "alacritty": 4,
  "arandr": 2,
  "azote": 4,
  "compton-conf": 2,
  "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom": 1,
  "env ATOM_DISABLE_SHELLING_OUT_FOR_ENVIRONMENT=false /usr/bin/atom ": 2,
  "geany ": 6,
  "gimp-2.10 ": 10,
  "inkscape ": 3,
  "pamac-manager ": 5
}
```

**Comment by Siborgium** [comment]
It seems this incovenience could be easily fixed by simply tweaking parser. In a few hours I'll push a solution.

**Comment by nwg-piotr** [comment]
Excellent. I'll be able to merge and get back to working on #99 this weekend.

**Comment by Siborgium** [comment]
This should revert the behaviour back.

**Comment by nwg-piotr** [comment]
Pinned look well, but it does not resolve the favourites issue. 

image

**Comment by Siborgium** [comment]
It happens because you have "corrupted" lines in your cache. Delete lines with trailing spaces and try again.

**Comment by nwg-piotr** [comment]
Duplicates && trailing spaces need to be removed.

**Comment by nwg-piotr** [comment]
That's what I'm talking about. User manual intervention required!

**Comment by Siborgium** [comment]
Users won't have this issue, so it doesn't look like a problem for me (trailing spaces were left by the forked version).

**Comment by nwg-piotr** [comment]
You may be right. Cache files on my Void Linux partition (packaged nwg-launchers version) look well.

**Comment by nwg-piotr** [comment]
Alright then: are we ready to merge?

**Comment by Siborgium** [comment]
Well... Let's test it once again, and, if nothing bad happens, I'd consider it ready.

**Comment by nwg-piotr** [comment]
OK, let it wait till tomorrow. 3:40 am here.

**Comment by nwg-piotr** [comment]
I did some performance testing, with [this reddit feedback](https://www.reddit.com/r/swaywm/comments/ihwclm/nwglaunchers_032_released/g34ao06/?utm_source=share&utm_medium=web2x&context=3) in mind. I **do not confirm** any gain on speed. Even if parsing is faster in fact, the overall performance decreased a little bit.

_Results below are obviously affected by the number of `.desktop` files, biggest on my development machine._

**My development laptop, AMD Ryzen 7 3750H, Radeon Vega Mobile Gfx, Arch Linux + sway**

| current master | your fork |
| --- | --- |
| 195 - 205 ms | 210 - 220 ms |

**Same on Void Linux + sway**

| current master | your fork |
| --- | --- |
| 85 - 95 ms | 90 - 100 ms |

**Testing laptop, Intel i3 @ 1.8 GHz, integrated graphics, ArchLabs Linux + sway**

| current master | your fork |
| --- | --- |
| 600 - 610 ms | 610 - 620 ms |

This is not a serious issue IMO, but it would make sense to pay attention to performance in further development.

**Comment by nwg-piotr** [comment]
## issue 4

This PR reverts #86

**Comment by nwg-piotr** [comment]
I'm going to merge and restore what's necessary.

**Comment by Siborgium** [comment]
>I do not confirm any gain on speed.

I **do** confirm. For me it is 420-430ms now vs 450-470ms before.

>restore what's necessary

My PR **does** account for `NoDisplay`. More precisely, if `desktop_entry(...)` encounters a `NoDisplay=true`, it returns an empty optional. I've removed `no_display = true` and all other checks for they are not needed. There is no reason to store entries we don't use.

> This explains the longer time of execution on my machine: more AppBoxes to create, as many of them were hidden previously.

It does not. I discard all entries with `NoDisplay=true`, there are not displayed, they are not even present in the vector of `DesktopEntry`. Take a look [here](https://github.com/Siborgium/nwg-launchers/tree/takealook). Build this branch, run and see the output.

**Comment by nwg-piotr** [comment]
> There is no reason to store entries we don't use

There is a reason. Please read this: https://wiki.archlinux.org/index.php/desktop_entries#Hide_desktop_entries

**Comment by nwg-piotr** [comment]
> Build this branch, run and see the output.

This branch brings back all the avahi* and Qt* stuff I turned off, back on my desktop. I copied their .desktop files to `.local/share/applications` and added the `NoDisplay=true` line in order not to see them any longer. Your branch discards my added entries, and finds them again in `/usr/share/applications`, w/o the `NoDisplay=true` line.

**Comment by Siborgium** [comment]
Oh. I misunderstood the overriding part.

I'll rework my implementation and open a PR as soon as possible. With your fix applied, my solution doesn't make any sense, so it should be either reverted back (undesired) or reworked.

**Comment by nwg-piotr** [comment]
Undoubtedly you'll do it better. My fix was intended a temporary solution.

**Comment by nwg-piotr** [comment]
This is a minor issue, but worth of mention. In filtered view, when I unpin an icon, it's being added to search results, though it does not meet the search criteria. Caja has just been unpinned:

image

**Comment by Siborgium** [comment]
Fixed. I'll open a PR when I get `NoDisplay` done.

**Pull request merged**
