### PR TITLE
Run nwggrid as daemon (#163)

### PR DESCRIPTION
**Pull request by Siborgium**
`nwggrid` takes too long to launch. This PR makes `nwggrid` run in the backround (#163) & show the window when requested.

TODO:
 - [ ] Provide unit file;
 - [x] Rewrite commit history to remove "WIP" commit messages;
 - [x] Rename nwggrid -> nwggrid-server, provide nwggrid wrapper launching;
 - [x] Provide "oneshot" option.

### CODE REVIEW

**Comment by Siborgium** [comment]
I've decided to postpone creating unit file as it requires certain changes on the way configuration works. I'll test it and merge in the next few days, together with an apropriate version bump.

**Comment by nwg-piotr** [comment]
> I'll test it and merge in the next few days

Very well. I'm not sure if you're able to release. If not, just let me know.

**Comment by Siborgium** [comment]
I want to fix one long-standing race condition during instance registration. The PR is otherwise ready.

**Comment by nwg-piotr** [comment]
> The PR is otherwise ready.

Sorry, couldn't take a look tonight. I had to fix two bugs in contributor's work in another project. I'll test tomorrow.

**Comment by Siborgium** [comment]
There's no rush :sweat_smile:

**Comment by nwg-piotr** [comment]
Sorry for the delay. I haven't even touched any code this week, due to health-related issues in the family.

nwggrid in client -  server mode seems to work very well. The only doubt I could name is: shouldn't the window state be reverted to the default state when shown back? Surely it's the matter of choice, but possibly such behavior would be more intuitive? I'm not sure.

**Comment by Siborgium** [comment]
Agreed, it's important to have nice & intuitive behaviour. I'll fix it today.

>health-related issues

Best wishes to you & your family.

**Comment by Siborgium** [comment]
It works, on my machine at least. Should I merge & release?

**Comment by nwg-piotr** [comment]
> Should I merge & release?

It's up to you. If you want me to test more carefully (I only tested the grid so far), I can do it later tonight.

**Comment by Siborgium** [comment]
Good, ping me when you're ready.

**Comment by nwg-piotr** [comment]
A bunch of minor issues:

## nwggrid as client-server:

For better keyboard support, when the window gets hidden and then shown back, either the first pinned item (if any) or the first app icon should grab focus. Otherwise the last focused item, possibly out of the screen at the moment, stays focused, and use of arrow keys scrolls the flowbox down unexpectedly.

## nwgbar

An error message about a file descriptor:

```text
$ nwgbar
INFO: wm: sway
INFO: 4 bar entries loaded
INFO: Using css file '"/home/piotr/.config/nwg-launchers/nwgbar/style.css"'

** (nwgbar:91193): WARNING **: 01:38:55.344: gtk-layer-shell v0.6.0 may not work on GTK v3.24.30. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
INFO: Time: 111ms
ERROR: Failed to unlock pid lock: Bad file descriptor
```

## nwgdmenu

This is probably a sway bug, which has nothing to do with your code, but I'm curious if you've experienced such a misbehaviour. Due to [this issue](https://github.com/swaywm/wlroots/issues/2636), still present in the current sway release, I had to switch to the Master branch. I'm not sure if the same happens on the released version.

When the window dimension decreases, the screen below the disappearing part won't get cleared. Instead, a part of the old window starts blinking. The latter rarely happen when wf-recorder works, so it's hard to notice in the video. Focusing another container clears the effect. The same happens to my nwg-dock, written in go, so this must be related to sway itself.

See the video: https://youtu.be/0F3vv_KoWAM

**Comment by Siborgium** [comment]
>When the window dimension decreases, the screen below the disappearing part won't get cleared. Instead, a part of the old window starts blinking. The latter rarely happens when wf-recorder works, so it's hard to notice in the video. Focusing another container clears the effect. The same affects my nwg-dock, written in go, so this must be related to sway itself.

It doesn't seem to glitch like that on wayfire. I'll check sway this evening and report back :)

**Comment by nwg-piotr** [comment]
> report back

Thanks in advance. I should install the released version, to check if the bug there's on the Master branch, but I still have something more urgent to do. Nights are too short. :)

**Comment by Siborgium** [comment]
(Un)fortunately I fail to reproduce the issue, it works fine.

**Comment by nwg-piotr** [comment]
Good to know, thanks! Hope it's not going to be present in the next release. Anyway, I think I should submit the issue.

**Comment by nwg-piotr** [comment]
Your latest fixes look perfectly well to me. However, I should have checked this earlier, sorry: hidden and shown back window should IMHO clear the search result, if any, for it to look as just started.

**Comment by nwg-piotr** [comment]
Looks excellent to me.

**Pull request merged**
