### PR TITLE
Rework structure

### PR DESCRIPTION
**Pull request by ericonr**
Ok, so in this PR:

- first two commits reorganizes stuff the way I did for bar.
- create a directory for common code - I made some changes to the `get_config_dir` function here, now it kills the application if it can't find `XDG_CONFIG_HOME` *and* `HOME`. I did this with `std::exit(1)`, would be glad to switch to an exception if we can fit one here.
- initial move for grid, dmenu and bar to the impls in `common/`
- move InputParser to common, use stderr for error message
- move some json and string functions to common
- create a template function for display geometry, since the functions were the same but used different types
- move AppBox to common

I also removed all def guards from the class declarations, since they shouldn't be needed. Everything both compiled and worked fine here. Further testing would be nice. If you'd like, I can split the PR into the first two commits and the others.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Whole lot of changes. Is there any simple way to test them before merging, other than applying changes locally file by file? Will cloning your `includes` branch do the job?

**Comment by ericonr** [comment]
I would clone the branch locally, yes. You can add my repo as another repo, fetch it, and checkout the `ericonr/includes` branch. That way you don't need to have another folder for it.

We should probably get some tests going for the applications, or at least a list of ways of launching them that tests lots of the functionality.

**Comment by nwg-piotr** [comment]
I'll need to set up a VM. I'm at the office with nothing special to do at the moment, but on M$ Windows. :/

**Comment by ericonr** [comment]
Good luck :D

**Comment by ericonr** [comment]
Btw, I put my copyright in the files I created, but if you feel like some of them should have yours / both of us, let me know.

**Comment by nwg-piotr** [comment]
I don't care as long as they are licensed under GPLv3.

**Comment by nwg-piotr** [comment]
Looks good to me. I only fixed my own bug by the way.

**Comment by nwg-piotr** [comment]
LOL, apart from the bug in /common/nwg_tools.cc line 29:

Instead of:

```
if (val) {
```

should be:

```
if (!val) {
```

**Comment by nwg-piotr** [comment]
There will also be some more debugging necessary, but this concerns my code.

**Pull request merged**
