### PR TITLE
Use sway-ipc instead of calling swaymsg

### PR DESCRIPTION
**Pull request by Siborgium**
This PR introduces SwaySock struct, handling Sway requests.

Before merging I'd like to discuss whether it should be in `nwg_tools` or moved into separate header/source file -- and take appropriate action.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
> whether it should be in `nwg_tools` or moved into separate header/source

What I hate most about C are headers, so my opinion is probably irrelevant. And it sounds: the less headers - the better. But if you see a possible new application for SwaySock in the future, it may be reasonable. Before merging this PR, we need to ask @ericonr if his current job is ready, and determine which PR should be merged first.

**Comment by Siborgium** [comment]
Cool! Thanks for quick reply, I am glad to help.

**Comment by nwg-piotr** [comment]
If I understand well, you have still some work to do before this PR is ready, right?

**Comment by Siborgium** [comment]
Yeah. Testing, mostly. Cleanup here and there.

**Comment by Siborgium** [comment]
As far as I could test, it works fine.

**Comment by nwg-piotr** [comment]
Seems to work well on my side, too.

**Pull request merged**
