### PR TITLE
Refactor + small fix

### PR DESCRIPTION
**Pull request by Siborgium**
I've put some effort into cleaning it up.

The only change I've noticed is that screen size is detected correctly now on my machine.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Looks good. However, in the meantime I added a temporary fix to `bar/bar_tools.cc`, which causes a conflict. I'll resolve it in the evening, when I'm back home.

**Comment by Siborgium** [comment]
Yeah, thanks. I'm going to push few commits more, just a bit of cleanup.

**Comment by nwg-piotr** [comment]
Very well. I just did my best to translate my old python code, but I'm still feeling lost in C++.

**Comment by Siborgium** [comment]
Let's consider it done.

**Pull request merged**
