### PR TITLE
Look for app dirs in XDG compliant fashion

### LINKED ISSUE #74: nwggrid shows no result
When I run nwggrid I don't see any apps. Even if I wait. There a 0 count at the bottom.

I wonder if I'm missing an icon theme or something.

nwg-launchers 0.2.0
sway
NixOS unstable

```
❯ nwggrid
WM: sway
Locale: fr
91 .desktop entries found
/home/bbigras/.config/nwg-launchers/nwggrid/style.css
Focused display: 0, 0, 1600, 900
Time: 104
```

### PR DESCRIPTION
**Pull request by Siborgium**
This should hopefully fix #74 
Please, test if it works and report back.

### CODE REVIEW

**Comment by bbigras** [comment]
It seems to work fine for me. :smile:

**Review by nwg-piotr — CHANGES_REQUESTED** [review]
It brakes the fix to #84. `.local/share/applications` must be the first checked location.

**Comment by Siborgium** [comment]
> `$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used. 

That's what my code does. If `$XDG_DATA_HOME` is set, we stick to it. Otherwise we fall back to hardcoded `~/.local/share/applications`.

If `$XDG_DATA_HOME=$HOME/.local/share:...`, `~/.local/share/applications` will be the first checked location.

**Comment by nwg-piotr** [comment]
Please... Whatever it does, hiding entries by adding a copy in `./local/share/applications` with the `NoDisplay=true` line no longer works.

**Comment by Siborgium** [comment]
I'll try to fix it.

**Comment by nwg-piotr** [comment]
Thanks! Surely wy could tell users to set the environment, but 90% does not read README.

**Comment by Siborgium** [comment]
We don't force anyone. XDG spec defines sensible fallbacks, and we try to use them. It should work anyway. If you are sure it is broken, please, give me more info.

**Comment by nwg-piotr** [comment]
I took my ancient testing laptop along with me to the office today. Will try to do some more testing.

**Comment by nwg-piotr** [comment]
My testing laptop runs a clean ArchLabs install + my sway configuration. No XDG data dirs are set.

```text
$ printenv | grep XDG
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_CLASS=user
XDG_VTNR=2
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1000
```
I copied all the avahi .desktop files (`avahi-discover.desktop`, `bssh.desktop` and `bvnc.desktop`) to `/home/piotr/.local/share/applications` and added the `NoDisplay=true` line at the bottom of each of them. This successfully prevents them from displaying in nwggrid built from the `master` branch. When I apply your latest changes, the icons appear again.

image

**Comment by Siborgium** [comment]
It turns out I've not synced local `master` with the latest `master`. Please, rebuild and report if it works. Toggling `NoDisplay=true` seems to work for me.

**Comment by nwg-piotr** [comment]
Due to the fact that the damned phone at the office keeps ringing, I can not pay as much attention to the code, as I should. However, I replaced `grid_tools.cc` and `grid_classes.cc` with your versions, built everything, and it seems to work well.

**Review by nwg-piotr — APPROVED** [review]

**Comment by Siborgium** [comment]
Cool!

**Comment by nwg-piotr** [comment]
As the new grid looks much better than the latest released version, it would be great to have a new release soon. Do you want me to wait for the reworked parsing you announced?

**Comment by colemickens** [comment]
Wow, thanks for the amazing turn-around time. Thanks @Siborgium, @nwg-piotr !

**Comment by bbigras** [comment]
Indeed. Thanks everyone. You too @colemickens

**Pull request merged**
