### PR TITLE
Let Configs handle all the configuration

### PR DESCRIPTION
**Pull request by Siborgium**
This draft aims to simplify configuration management. Currently all the variables (alignment, css paths, icon size, ...) are scattered across `main`, making tweaking harder. A lot of them are duplicated, tripling the work needed to fix/change something. We already have `Config` struct configuring `CommonWindow`, so now we just need to extend this approach to all other pieces of code.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Do not forget to update the documentation when it's done.

**Comment by Siborgium** [comment]
The title is a bit misleading, I guess. There aren't any behavioural changes, I'm just moving the code responsible for setting up configuration to Config struct and it's successors. It's more of a cleanup.

**Review by Siborgium — COMMENTED** [review]
Glib lets us print nice error message to user if something went wrong and doesn't depend on '&' appended.

**Comment by Siborgium** [comment]
I'll merge this pr after #167

**Pull request merged**
